scalyr/dataset-go

- .github/workflows/code-quality.yaml
- .github/workflows/secrets-scanner.yaml
- README.md
- codecov.yml
This pull request adds GHA workflow and codecov.io status badge to the readme.
It also removes codecov token from the workflow - this token is not needed anymore for integration now that this repo is public.
> Add status badges to the readme

- .gitignore
- Makefile
- RELEASE_NOTES.md
- pkg/buffer/buffer.go
- pkg/client/add_events.go
- pkg/client/add_events_long_running_test.go
- pkg/client/add_events_test.go
- pkg/client/client.go
- pkg/version/version.go
- pkg/version/version_test.go
When many events are pushed through the collector, sometimes more and sometimes less events then expected is received. Lets figure out why.
Add unit test, that creates many batches and sends them to the server. Check that each event was processed once.
There are also following changes:
* buffer sweeper is skipping buffers that are receiving events and marks them for immediate publishing
* I have added more comments to make it clearer
* 
When I run: `make test-many-times COUNT=30` - it always succeeds.
I have added also identical code into datasetexporter code, but there it always shows data race somewhere. Also less than 20 items out of 200k gets lost:
```
logs_exporter_e2e_test.go:274: Failed test 'processed items'
DATA: values differ
got: (uint64) 199984
expected: (uint64) 200000 …
```
> DSET-1556: Add test to check that each event is processed once

- RELEASE_NOTES.md
- pkg/client/add_events.go
- pkg/client/client.go
- pkg/version/version.go
- pkg/version/version_test.go
When many events are pushed through the collector, sometimes more and sometimes less events then expected is received. Lets figure out why.
Although I was trying to solve in the #12 and #13, I was not successful. The problem is that function `AddEvents` could be called multiple times in parallel. I was not expecting this. Current implementation is not able to deal with it, so let's add Lock to make sure that it's called only once.
There are many ways how it can be solved, but it's not clear which one is the best. So lets for now, just allow single call at once - and solve It properly after the long weekend.
When I run: `make test-many-times COUNT=30` - it always succeeds.
I have added identical code into `datasetexporter` and it passes there as well.
> DSET-1556: Run AddEvents one at a time

- .github/workflows/code-quality.yaml
Let's run integration tests fewer times. There is no need to wait 50 minutes to get results.
> DSET-1556: Run integration tests fewer times

- RELEASE_NOTES.md
- examples/client/go.sum
- examples/readme/go.sum
- pkg/client/add_events.go
- pkg/client/add_events_long_running_test.go
- pkg/client/add_events_test.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/version/version.go
- pkg/version/version_test.go
In the PR #14 I have added one global mutex that allowed only single call of `AddEvents` function at once. In this PR make it more granular.
Although I was trying to solve in the #12 and #13, I was not successful. I have quick solved it in #14. This PR contains more proper fix. Idea is to introduce another queue. The current logic is:
* Add each event into topic based on the key
* For each topic there is subscriber that reads those messages. 
* Read messages are added into buffer. Once the buffer is full add into into different pub/sub where topic is key
* For each topic there is subscriber, that reads those buffers and calls API to publish them
When I run: `make test-many-times COUNT=30` - it always succeeds.
I have added identical code into `datasetexporter` and it passes there as well.
> DSET-3833: Handle parallel calls of AddEvents

- Makefile
- pkg/buffer/buffer_test.go
- pkg/client/add_events_test.go
In PR #20 I have switched testing framework. There are still some flaky tests.
Fix flaky tests. It looks that the issue is with tests depends on timing and GitHub is slower, so some number of retries is different.
* When I run: `make test-many-times COUNT=10` - it always succeeds.
> DSET-2106: Fix flaky tests first

- pkg/client/add_events.go
- pkg/client/client.go
Log statistics more often and include also duration in seconds.
To be able to benchmark it, we should now for how long it's running and whether all the expected events were processed. To be able to do that, we have to log statistics more often and include more information.
Same as PR #27
> DSET-3951: Log statistics more often with duration as well

- pkg/client/add_events.go
- pkg/client/add_events_test.go
- pkg/client/client.go
- pkg/client/client_test.go
This pull request updates ``apiCall()`` function to also log partial raw response body in case we fail to parse response body as JSON.
This will help troubleshooting various edge cases when the API doesn't return valid JSON.
> [DSET-4072] Include (truncated) response body in the error message in case we fail to parse the response body

- pkg/client/add_events_test.go
- pkg/client/client.go
Problem
- when DataSet returns Retryable error we try to retry with timeout. Once this time is over we stay in error mode since last error is never overriden, and new event handling is rejected.
Solution
- keep timestamp of last error and consider it while evaluate last error timestamp in order to recover from error mode.
> DSET-4080 fix recovery from error state

- examples/client/main.go
- examples/readme/main.go
- pkg/api/request/request.go
- pkg/api/request/request_test.go
- pkg/client/add_events.go
- pkg/client/add_events_long_running_test.go
- pkg/client/add_events_test.go
- pkg/client/client.go
- pkg/client/client_test.go
In order to improve telemetry lets propagate 
- OtelCollector attributes to
- library version
- OS details
to User-Agent header
> DSET-3467 feature: add more details to User-Agent header

- RELEASE_NOTES.md
- pkg/version/version.go
- pkg/version/version_test.go
To be able to use #39 from the `datasetexporter` in the [opentelemetry](https://github.com/open-telemetry/opentelemetry-collector-contrib) we have to release new version with higher tag.
So let's release it.
> DSET-4002: Release version 0.0.10

- Makefile
- examples/client/go.sum
- examples/client/main.go
- examples/readme/go.sum
- examples/readme/main.go
- pkg/client/add_events.go
- pkg/client/add_events_long_running_test.go
- pkg/client/add_events_test.go
Make the logging during shutdown less confusing.
During the shutdown process some of the events and buffers may not be processed yet. We have been logging messages like - "not all buffers has been processed". This was misleading since it was expected. Also log more clearly when the shutdown has started and when finished.
> DSET-4050: Improve logging related to shutting down the client

- .github/workflows/code-quality.yaml
- .pre-commit-config.yaml
Our CI pipeline for is failing a lot in the step that is trying to upload results to CodeCov. There is the following issue - https://github.com/codecov/codecov-action/issues/557 - where people have the same problem. Their fix is to explicitly include the CODECOV_TOKEN in the step.
So I am doing the same change and we will see, whether this will help or not.
> CodeCov: Explicitly specify token

- .pre-commit-config.yaml
- scripts/install-dev-tools.sh
Code quality check is not reliable since it's failing all the time on some strange errors.
```
go test -v -race -timeout 360s -parallel 4 -count=1 -tags=long_running,"" ./...
Error: pkg/buffer_config/buffer_config.go:23:2: cannot find package "." in:
/home/runner/work/dataset-go/dataset-go/vendor/github.com/cenkalti/backoff/v4
Error: pkg/buffer/buffer.go:32:2: cannot find package "." in:
/home/runner/work/dataset-go/dataset-go/vendor/github.com/google/uuid
Error: pkg/client/client.go:44:2: cannot find package "." in:
/home/runner/work/dataset-go/dataset-go/vendor/github.com/cskr/pubsub
make: *** [Makefile:56: test-all] Error 1
Error: Process completed with exit code 2.
```
Let's try to fix this.
I have removed `dnephin/pre-commit-golang` - pre-commit hook - …
> Fix failing pre-commit checks

- Makefile
- RELEASE_NOTES.md
- pkg/buffer_config/buffer_config.go
- pkg/buffer_config/buffer_config_test.go
- pkg/client/add_events.go
- pkg/client/add_events_long_running_test.go
- pkg/client/add_events_test.go
- pkg/config/config_test.go
- pkg/version/version.go
- pkg/version/version_test.go
When we have introduced `RetryShutdownTimeout` in the PR #44, we have introduced a bug where if the value is set to 0, then it retries indefinitely - https://pkg.go.dev/github.com/cenkalti/backoff/v4#ExponentialBackOff.
The test `add_events_long_running_test.go` was flaky, because its as called shutdown immediately after all the events has been submitted asynchronously. There was not enough time to process them and therefore they have been failing.
This PR is also increasing version to 0.12.0
> DSET-4359: Fix flaky tests

- .github/workflows/code-quality.yaml
- pkg/client/add_events.go
- pkg/client/add_events_long_running_test.go
- pkg/client/client.go
- pkg/version/version.go
- pkg/version/version_test.go
In the PR #46 I was hoping to fix the flaky tests. Although it is not failing on my machine and when I have run it few times as GitHub Action - it's still not clear why there is still sometimes lost event. So let's introduce more metrics to measure also lost/broken stuff to see, what is going on.
This is the flaky test - https://github.com/scalyr/dataset-go/blob/main/pkg/client/add_events_long_running_test.go - out of 200k events there is 10% chance, that one event gets lost.
There is 200_000 events enqueued in the function `AddEvents` and it's tracked by `client.eventsEnqueued`, but there is only 199_999 events processed by the function `listenAndSendBundlesForKey` and it's tracked by `client.eventsProcessed`.
There are also variables to keep track of dropped (`client.eventsDropped`) or …
> Fix flaky tests: Add more metrics

- .github/workflows/unit-tests.yaml
- pkg/buffer/buffer_test.go
- test/testdata/buffer_test_payload_full.json
Jira Link: <https://sentinelone.atlassian.net/browse/4430}>
When tests are executed on Windows, there is a flaky test - https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/25094 - so lets run the library tests on Windows as well.
Add GitHub action that runs tests on all supported version - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
Check that GHA is running those tests.
> DSET-4430: Fix flaky test on Windows

- .github/workflows/code-quality.yaml
- .github/workflows/unit-tests.yaml
- Makefile
- README.md
Jira Link: <https://sentinelone.atlassian.net/browse/DSET-4430>
Run the same OS and Go version as Open Telemetry Contrib
In the PR #50 we have started to run tests also on Windows. But we should test as well with Go 1.20, since it's used by OpenTelemetry as well - OpenTelemetryContrib is running tests for Go 1.20 as well - https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/build-and-test.yml#L225
Test for Go 1.19 and 1.20 are executed.
> DSET-4430: Test also Go 1.20

- RELEASE_NOTES.md
- pkg/client/add_events.go
- pkg/client/add_events_long_running_test.go
- pkg/client/add_events_test.go
- pkg/client/client.go
- pkg/client/statistics.go
- pkg/version/version.go
- pkg/version/version_test.go
Jira Link: <https://sentinelone.atlassian.net/browse/DSET-4449>
In the PR #47 I have added counting for dropped and broken buffers. However I haven't adjusted the counting for processed buffers. So when the buffer was dropped we have counted it twice - `enqueued < processed + dropped`.
I have refactored the function `DatasetClient.logStatistics()` into two functions - `DatasetClient.Statistics()`, which count the statistics,  and `DatasetClient.logStatistics()`, which logs statistics.
So after fixing that bug it allowed me to write tests to verify that the statistics are computed correctly.
Add unit tests.
> DSET-4449: Do not count dropped buffer as processed

- examples/client/main.go
- examples/readme/main.go
- pkg/client/add_events_test.go
- pkg/client/client.go
- pkg/meter_config/meter_config.go
- pkg/meter_config/meter_config_test.go
- pkg/statistics/statistics.go
- pkg/statistics/statistics_test.go
- pkg/version/version.go
Jira Link: https://sentinelone.atlassian.net/browse/DSET-4558
I have received feedback in the PR in the Otel Contrib - https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/29446#issuecomment-1827431693 that:
* metric names should be `snake_case`
* there should be support for attributes
I have renamed the metrics as well as introduced possibility to pass the processing entities as well as name.
Same as in the PR #61 
But add more dataset exporters in the demo repository - `src/otelcollector/otelcol-config.yml`
```
service:
pipelines:
traces:
receivers: [otlp]
processors: [batch, attributes]
exporters: [otlp, debug, spanmetrics, dataset, dataset/aaa, dataset/bbb, dataset/ccc, dataset/ddd]
metrics:
receivers: [httpcheck/frontendproxy, otlp, spanmetrics, prometheus] …
```
> Metrics: add attributes and switch to snake_case

- .github/workflows/code-quality.yaml
- .github/workflows/stress-tests.yaml
- .github/workflows/unit-tests.yaml
- examples/client/go.mod
- examples/readme/go.mod
- examples/stress/go.mod
- examples/stress/go.sum
- go.mod
Go 1.21 is dead now. So lets deprecate it and use 1.23.
https://endoflife.date/go
> Replace Go 1.21 with Go 1.23
